export async function runBookmarkDeletionTests({ fixtures, left, right, row, parentRow, checkbox, selectedRow, open, until, command, clickCommand, focus, mark }) {
  const results = [];
  const assert = (condition, message) => {
    if (!condition) throw new Error(message);
    results.push(message);
  };
  const folder = await browser.bookmarks.create({ parentId: fixtures.id, title: 'Deletion fixtures' });
  const first = await browser.bookmarks.create({ parentId: folder.id, title: 'Delete first', url: 'about:blank' });
  const branch = await browser.bookmarks.create({ parentId: folder.id, title: 'Delete folder' });
  const child = await browser.bookmarks.create({ parentId: branch.id, title: 'Delete child', url: 'about:blank' });
  await browser.bookmarks.create({ parentId: folder.id, title: 'Delete middle', url: 'about:blank' });
  await browser.bookmarks.create({ parentId: folder.id, title: 'Delete last', url: 'about:blank' });
  const separator = await browser.bookmarks.create({ parentId: folder.id, type: 'separator', index: 0 });
  const originalRemove = browser.bookmarks.remove;
  const originalRemoveTree = browser.bookmarks.removeTree;
  const originalConfirm = window.confirm;
  const confirmations = [];
  let confirmationAllowed = false;
  window.confirm = (message) => {
    confirmations.push(message);
    return confirmationAllowed;
  };
  let release = () => {};
  try {
    for (const pane of [left, right]) parentRow(pane).dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
    await until(() => row(left, folder.title) && row(right, folder.title));
    open(left, folder.title);
    open(right, folder.title);
    await until(() => row(left, 'Delete last') && row(right, 'Delete last'));
    await mark(left, first.title);
    await mark(left, branch.title);
    await mark(right, 'Delete middle');
    await focus(left, 'Delete last');
    clickCommand('Всё');
    await until(() => left.querySelectorAll('input:checked').length === 4);
    assert(right.querySelectorAll('input:checked').length === 1 && checkbox(left, branch.title).checked && document.activeElement === row(left, 'Delete last') && command('Всё').disabled && left.querySelector('header').textContent.includes('Выбрано: 4'), 'Select-all completes partial left selection with folders and bookmarks, excludes parent and separator rows and preserves focus and right marks');
    clickCommand('Ничего');
    await until(() => !left.querySelector('input:checked'));
    assert(checkbox(right, 'Delete middle').checked && document.activeElement === row(left, 'Delete last') && command('Ничего').disabled && !left.querySelector('header').textContent.includes('Выбрано:'), 'Clear selection removes only active pane marks and count while retaining focus and the other pane selection');
    await focus(right, 'Delete middle');
    clickCommand('Всё');
    await until(() => right.querySelectorAll('input:checked').length === 4);
    assert(!left.querySelector('input:checked') && document.activeElement === row(right, 'Delete middle') && command('Всё').disabled, 'Select-all operates on the active right pane and preserves the empty left selection');
    clickCommand('Ничего');
    await until(() => !right.querySelector('input:checked'));
    assert(document.activeElement === row(right, 'Delete middle') && command('Ничего').disabled, 'Clear selection also operates on the active right pane without changing its focus');
    await browser.bookmarks.remove(separator.id);
    await until(() => !left.querySelector(`[data-bookmark-id="${separator.id}"]`) && !right.querySelector(`[data-bookmark-id="${separator.id}"]`));
    open(right, branch.title);
    await until(() => row(right, child.title));
    await mark(left, first.title);
    await mark(left, branch.title);
    await focus(left, 'Delete middle');
    let calls = 0;
    let held = false;
    const gate = new Promise((resolve) => { release = resolve; });
    browser.bookmarks.remove = async (...args) => {
      calls++;
      const removed = await originalRemove(...args);
      held = true;
      await gate;
      return removed;
    };
    browser.bookmarks.removeTree = async (...args) => { calls++; return originalRemoveTree(...args); };
    clickCommand('Удалить');
    await new Promise((resolve) => setTimeout(resolve, 50));
    assert(calls === 0 && row(left, first.title) && row(left, branch.title) && left.querySelectorAll('input:checked').length === 2 && document.activeElement === row(left, 'Delete middle') && !command('Удалить').disabled, 'Cancelling deletion confirmation makes no bookmark API calls and preserves marks and focus');
    assert(confirmations.length === 1 && confirmations[0].includes('Количество элементов: 2.') && confirmations[0].includes('Папки будут удалены вместе с содержимым.'), 'Deletion confirmation shows the selected item count and explains recursive folder deletion');
    confirmationAllowed = true;
    clickCommand('Удалить');
    await until(() => held);
    await new Promise((resolve) => setTimeout(resolve, 80));
    assert(row(left, first.title) && row(left, branch.title) && left.querySelectorAll('input:checked').length === 2 && [...document.querySelectorAll('[aria-label="Команды"] button')].every((button) => button.disabled), 'A delete batch freezes visible rows and marks and disables every command');
    clickCommand('Удалить');
    assert(calls === 1 && confirmations.length === 2, 'A second delete cannot overlap an active batch or open another confirmation');
    release();
    await until(() => !row(left, first.title) && !row(left, branch.title) && !parentRow(right) && !command('Удалить').disabled);
    assert(document.activeElement === row(left, 'Delete middle') && !left.querySelector('input:checked'), 'Deleting checked bookmarks and folders preserves an unmarked focused row and clears removed marks');
    const removed = await Promise.all([first.id, branch.id, child.id].map((id) => browser.bookmarks.get(id).catch(() => [])));
    assert(removed.every((nodes) => nodes.length === 0) && right.querySelector('h2').textContent === 'Все закладки', 'Folder deletion removes its entire subtree and returns a pane opened inside that subtree to the root');
    browser.bookmarks.remove = originalRemove;
    browser.bookmarks.removeTree = originalRemoveTree;
    selectedRow(right).focus();
    await until(() => document.activeElement === selectedRow(right));
    assert(command('Удалить').disabled, 'Delete cannot remove the Firefox root folders');

    await focus(left, 'Delete last');
    clickCommand('Удалить');
    assert(confirmations.at(-1).includes('Количество элементов: 1.'), 'Deletion confirmation counts the focused row as one item when no checkboxes are marked');
    await until(() => !row(left, 'Delete last') && !command('Удалить').disabled);
    assert(document.activeElement === row(left, 'Delete middle') && !left.querySelector('input:checked'), 'Deleting a focused unmarked last row selects the nearest remaining row');
    const last = await browser.bookmarks.create({ parentId: folder.id, title: 'Delete retry', url: 'about:blank' });
    await until(() => row(left, last.title));
    await mark(left, 'Delete middle');
    await mark(left, last.title);
    await focus(left, last.title);
    calls = 0;
    browser.bookmarks.remove = async (...args) => {
      if (++calls === 2) throw new Error('Injected bookmark deletion failure');
      return originalRemove(...args);
    };
    clickCommand('Удалить');
    await until(() => document.querySelector('[role="alert"]') && !command('Удалить').disabled);
    assert(!row(left, 'Delete middle') && checkbox(left, last.title).checked && document.activeElement === row(left, last.title), 'A partial deletion failure reports the error and keeps the remaining item marked and focused');
    browser.bookmarks.remove = originalRemove;
    clickCommand('Удалить');
    assert(confirmations.at(-1).includes('Количество элементов: 1.'), 'Retry confirmation counts only the remaining marked item after a partial deletion');
    await until(() => !row(left, last.title) && !document.querySelector('[role="alert"]'));
    assert(document.activeElement === parentRow(left) && command('Удалить').disabled && command('Ничего').disabled, 'Retry deletes only the remaining mark, clears the error and focuses the parent entry without allowing its deletion');
    parentRow(left).dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
    const [toolbar] = await browser.bookmarks.get(fixtures.parentId);
    open(right, toolbar.title);
    await until(() => row(right, fixtures.title));
    open(right, fixtures.title);
    await until(() => row(left, folder.title) && row(right, folder.title));
    await browser.bookmarks.removeTree(folder.id);
    await until(() => !row(left, folder.title) && !row(right, folder.title));
    return results;
  } finally {
    release();
    browser.bookmarks.remove = originalRemove;
    browser.bookmarks.removeTree = originalRemoveTree;
    window.confirm = originalConfirm;
  }
}
